# Site settings
title: Great New Blog Title
author:
  name: Salman K.H
  email: salmankh47@github.com
description: "Great site about Jekyll on GH-Pages."

# Build settings
remote_theme: jekyll/minima
